networks:
  traefik:
    external: true

services:
  app:
    build:
      context: .
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_GOOGLE_API_KEY: ${VITE_GOOGLE_API_KEY}
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.jat.rule=Host(`apply.whitney.rip`)
      - traefik.http.routers.jat.tls=true
      - traefik.http.routers.jat.tls.certresolver=lets-encrypt
      - traefik.http.services.jat.loadbalancer.server.port=80
      - traefik.port=80